/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.tarifas.simples;

import command.tarifas.CargarTarifasCommand;
import command.tarifas.CargarTarifasNocturnoCommand;
import command.tarifas.CargarTiposDeTarifaCommand;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import model.Tarifas.Tarifa;
import model.Tarifas.TarifaNocturno;
import model.Tarifas.TipoDeTarifa;
import process.CRUDTarifas.AsociarTipoDeTarifaACliente;
import process.CRUDTarifas.EliminarTipoDeTarifaACliente;
import process.cargador.tarifas.CargadorListaTarifas;
import process.cargador.tarifas.CargadorListaTarifasNocturno;
import process.cargador.tarifas.CargadorListaTiposDeTarifa;
import process.parser.tarifas.TarifaNocturnoParserJson;
import process.parser.tarifas.TarifaParserJson;
import process.parser.tipoDeTarifas.TipoDeTarifaParserJson;
import view.fichaCliente.FichaCliente;
import view.tarifas.tiposDeTarifas.JTablaTiposDeTarifas;
import view.tarifas.tiposDeTarifas.TiposDeTarifaCRUDFrame;

/**
 *
 * @author loquat
 */
public final class AsociarTarifasAClienteFrame extends javax.swing.JFrame {

    /**
     * Creates new form AsociarTarifasAClienteFrame
     * @param listaLosTiposDelCliente
     * @param listaTodosLosTipos
     * @throws java.io.IOException
     */
    
    
    
    
     JTablaTiposDeTarifas tablaTipos;
     JTablaTiposDeTarifas tablaTiposCliente;
     List<TipoDeTarifa> listaLosTiposDelCliente;
     List<TipoDeTarifa> listaTodosLosTipos;
   
     FichaCliente ficha;
     Integer idCliente;
     
    
    public AsociarTarifasAClienteFrame(FichaCliente ficha) throws IOException {
        this.ficha = ficha;
        
        initComponents();
        tablaTipos = new JTablaTiposDeTarifas();
        tablaTiposCliente = new JTablaTiposDeTarifas();
        
        this.listaLosTiposDelCliente = ficha.getListaTiposDelCliente();
        this.listaTodosLosTipos = ficha.getListaTodosLosTipos();
      

      
        tablaTiposCliente.mostrarTarifas(listaLosTiposDelCliente);
        tablaTipos.mostrarTarifas(listaTodosLosTipos);
        
        
        jScrollPaneTOTAL.setViewportView(tablaTipos);
        jScrollPaneCLIENTE.setViewportView(tablaTiposCliente);
        
        
       this.idCliente = ficha.getIdCliente();
        actualizarListas();
        
        
    }
    
    public void actualizarListas() throws IOException {
    
           CargarTarifasCommand cargar = new CargarTarifasCommand(new CargadorListaTarifas(), new TarifaParserJson());
           CargarTarifasNocturnoCommand cargarNocturno = new CargarTarifasNocturnoCommand(new CargadorListaTarifasNocturno(), new TarifaNocturnoParserJson());
           CargarTiposDeTarifaCommand cargarTipos = new CargarTiposDeTarifaCommand(new CargadorListaTiposDeTarifa(), new TipoDeTarifaParserJson());
           List<Tarifa> listaTarifasDiurno  =  cargar.executeLista(idCliente);
           List<TarifaNocturno> listaTarifasNocturno =  cargarNocturno.executeListaNocturno(idCliente);
           
           listaLosTiposDelCliente = new ArrayList<>();
             this.listaTodosLosTipos = ficha.getListaTodosLosTipos();
      
          
           for (Tarifa lista1 : listaTarifasDiurno) {
                for (int j=0;j<listaTodosLosTipos.size();j++) {
                    if (lista1.getTipoDeTarifa().equals(listaTodosLosTipos.get(j).getId())) {
                        TipoDeTarifa tipo = new TipoDeTarifa();
                        tipo.setTipo(listaTodosLosTipos.get(j).getTipo());
                        tipo.setId(listaTodosLosTipos.get(j).getId());
                        listaLosTiposDelCliente.add(tipo);

                    }
                }
            }
            
            cargarNocturno.executeListaNocturno(idCliente);
            ficha.actualizarListaTarifas(listaTarifasDiurno, listaTarifasNocturno, listaLosTiposDelCliente);
            tablaTiposCliente.mostrarTarifas(listaLosTiposDelCliente);
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        botonAddFecha = new javax.swing.JButton();
        jScrollPaneTOTAL = new javax.swing.JScrollPane();
        jScrollPaneCLIENTE = new javax.swing.JScrollPane();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("ASOCIACIÓN DE TARIFAS A CLIENTE");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel47.setBackground(new java.awt.Color(51, 51, 255));
        jLabel47.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel47.setForeground(new java.awt.Color(51, 51, 51));
        jLabel47.setText("LISTADO TARIFAS");

        jLabel48.setBackground(new java.awt.Color(51, 51, 255));
        jLabel48.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel48.setForeground(new java.awt.Color(51, 51, 51));
        jLabel48.setText("LISTADO TARIFAS DEL CLIENTE");

        botonAddFecha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/diasFestivos/arrow.png"))); // NOI18N
        botonAddFecha.setText("jButton1");
        botonAddFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAddFechaActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/tarifas/simples/flecha1.PNG"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton2.setText("Configuración de tarifas");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel47)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPaneTOTAL, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(30, 30, 30)
                                        .addComponent(jButton1))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(botonAddFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(12, 12, 12)))))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel48)
                            .addComponent(jScrollPaneCLIENTE, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(228, 228, 228)
                        .addComponent(botonAddFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel47)
                            .addComponent(jLabel48))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPaneTOTAL, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPaneCLIENTE, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonAddFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAddFechaActionPerformed
        boolean encontrado = false;
           for (int j=0; j<listaLosTiposDelCliente.size(); j++) {
               if (listaTodosLosTipos.get(tablaTipos.getSelectedRow()).getTipo().equals(listaLosTiposDelCliente.get(j).getTipo())) {
                        JOptionPane.showMessageDialog(null,"Esta tarifa ya esta asociada");
                       encontrado = true;
                           break;
               }  
             
            
            
        }
        if (encontrado == false) {
        
        AsociarTipoDeTarifaACliente asociador = new AsociarTipoDeTarifaACliente(listaTodosLosTipos.get(tablaTipos.getSelectedRow()), idCliente);
        try {
            asociador.asociar();
            actualizarListas();

        } catch (Exception ex) {
            Logger.getLogger(AsociarTarifasAClienteFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
    }//GEN-LAST:event_botonAddFechaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        EliminarTipoDeTarifaACliente eliminador = new EliminarTipoDeTarifaACliente(listaLosTiposDelCliente.get(tablaTiposCliente.getSelectedRow()), idCliente);
         try {
             eliminador.eliminar();
               actualizarListas();
         } catch (Exception ex) {
             Logger.getLogger(AsociarTarifasAClienteFrame.class.getName()).log(Level.SEVERE, null, ex);
         }
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       TiposDeTarifaCRUDFrame.getInstance().setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAddFecha;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPaneCLIENTE;
    private javax.swing.JScrollPane jScrollPaneTOTAL;
    // End of variables declaration//GEN-END:variables
}
