/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.avisos;

import command.serviciosEspeciales.CargarServiciosEspecialesCommand;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import model.Aviso;
import model.serviciosEspeciales.ServicioEspecial;
import process.cargador.serviciosEspeciales.CargadorListaServiciosEspeciales;
import process.parser.serviciosEspeciales.ServicioEspecialParserJson;
import view.serviciosEspeciales.JTablaServiciosEspeciales;

/**
 *
 * @author gruasjoseantonio
 */
public class FrameServiciosEspecialesCliente extends javax.swing.JFrame {
   JTablaServiciosEspeciales tablaServiciosEspeciales;
   Aviso aviso;
  
   public FrameServiciosEspecialesCliente(Aviso aviso) {
        initComponents();
         try{
            this.aviso = aviso;
            this.setLocationRelativeTo(null);
            llenarTablaServiciosEspeciales();
            pack();
   
         
         } catch (Exception ex) {
            Logger.getLogger(FrameServiciosEspecialesCliente.class.getName()).log(Level.SEVERE, null, ex);
        }
         
        pack();
         
       // this.setSize(Toolkit.getDefaultToolkit().getScreenSize());
      
    }
    
    private void llenarTablaServiciosEspeciales() throws Exception {
        tablaServiciosEspeciales = new JTablaServiciosEspeciales();
       
        CargarServiciosEspecialesCommand cargar = new CargarServiciosEspecialesCommand(new CargadorListaServiciosEspeciales(), new ServicioEspecialParserJson());
       
        List<ServicioEspecial> listaServiciosEspecialesDelCliente  =  cargar.executeLista(aviso.getIdCliente());
        tablaServiciosEspeciales.mostrarServiciosEspeciales(listaServiciosEspecialesDelCliente);
       
        jScrollPaneTablaServiciosEspeciales.setViewportView(tablaServiciosEspeciales);
      
    
    }
    
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPaneTablaServiciosEspeciales = new javax.swing.JScrollPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Seleccion Servicio Especial Para Aviso");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPaneTablaServiciosEspeciales, javax.swing.GroupLayout.PREFERRED_SIZE, 1316, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPaneTablaServiciosEspeciales, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPaneTablaServiciosEspeciales;
    // End of variables declaration//GEN-END:variables
}
