/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.basesOperativas;

import DatosPrecargados.SingletonBasesOperativas;
import command.basesOperativas.CargarBasesOperativasCommand;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import model.basesOperativas.BaseOperativa;
import process.CRUDBasesOperativas.AsociarBaseOperativaACliente;
import process.CRUDBasesOperativas.EliminarBaseOperativaACliente;
import process.cargador.CargadorListaBasesOperativas;
import process.parser.basesOperativas.BaseOperativaParserJson;
import view.fichaCliente.FichaCliente;
import view.fichaCliente.SingletonCliente;

/**
 *
 * @author loquat
 */
public class AsociarBasesOperativasAClienteFrame extends javax.swing.JFrame {

     JTablaBasesOperativasVista tablaBasesOperativas;
     JTablaBasesOperativasVista tablaBasesOperativasDelCliente;
     List<BaseOperativa> listaBasesDelCliente;
     CargarBasesOperativasCommand cargar;
  
     public AsociarBasesOperativasAClienteFrame() throws IOException {
        initComponents();
        this.setLocationRelativeTo(null);
        tablaBasesOperativas = new JTablaBasesOperativasVista();
        tablaBasesOperativasDelCliente = new JTablaBasesOperativasVista();
        tablaBasesOperativas.getColumnModel().getColumn(0).setPreferredWidth(0);
        tablaBasesOperativasDelCliente.getColumnModel().getColumn(0).setPreferredWidth(0);
       
        cargar = new CargarBasesOperativasCommand(new CargadorListaBasesOperativas(), new BaseOperativaParserJson());
        listaBasesDelCliente = cargar.executeLista(SingletonCliente.getInstance().getCliente().getId());
        tablaBasesOperativasDelCliente.mostrar(listaBasesDelCliente);
        tablaBasesOperativas.mostrar(SingletonBasesOperativas.getInstance().getLista());
           
        jScrollPaneCLIENTE.setViewportView(tablaBasesOperativasDelCliente);
        jScrollPaneTOTAL.setViewportView(tablaBasesOperativas);
        
        addWindowListener( new WindowAdapter() {
                @Override
                public void windowClosing( WindowEvent evt ) {
                  
                        try {
                            actualizarListas();
                        } catch (Exception ex) {
                            Logger.getLogger(AsociarBasesOperativasAClienteFrame.class.getName()).log(Level.SEVERE, null, ex);
                        }
                        
                        
                   
                    
                }
            });
        
        
        
    }

    public void actualizarListas() throws IOException, Exception {
           SingletonBasesOperativas.getInstance().actualizarLista();
           listaBasesDelCliente  =  cargar.executeLista(SingletonCliente.getInstance().getCliente().getId());
          
           tablaBasesOperativasDelCliente.mostrar(listaBasesDelCliente);
           tablaBasesOperativas.mostrar(SingletonBasesOperativas.getInstance().getLista());
           FichaCliente.getInstance(SingletonCliente.getInstance().getCliente().getId()).getFichaModelo().actualizarBasesOperativas(listaBasesDelCliente);
           
       
    
    }
     
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPaneTOTAL = new javax.swing.JScrollPane();
        jScrollPaneCLIENTE = new javax.swing.JScrollPane();
        jButton1 = new javax.swing.JButton();
        botonAddFecha = new javax.swing.JButton();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/tarifas/simples/flecha1.PNG"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        botonAddFecha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/diasFestivos/arrow.png"))); // NOI18N
        botonAddFecha.setText("jButton1");
        botonAddFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAddFechaActionPerformed(evt);
            }
        });

        jLabel47.setBackground(new java.awt.Color(51, 51, 255));
        jLabel47.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel47.setForeground(new java.awt.Color(51, 51, 51));
        jLabel47.setText("LISTADO TOTAL DE BASES OPERATIVAS");

        jLabel48.setBackground(new java.awt.Color(51, 51, 255));
        jLabel48.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel48.setForeground(new java.awt.Color(51, 51, 51));
        jLabel48.setText("LISTADO DE BASES OPERATIVAS DEL CLIENTE");

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/basesOperativas/iconoconfiguracion.png"))); // NOI18N
        jButton2.setText("Configuración de bases operativas");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPaneTOTAL, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButton1)
                                    .addComponent(botonAddFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel47))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPaneCLIENTE, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel48))
                        .addGap(23, 23, 23))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(botonAddFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)
                        .addComponent(jButton1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel47)
                            .addComponent(jLabel48))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPaneCLIENTE, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPaneTOTAL, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonAddFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAddFechaActionPerformed
       
        
        Iterator<BaseOperativa> iter = listaBasesDelCliente.iterator();
      
        Boolean encontrado = false;
        while (iter.hasNext()) {
            Integer id = iter.next().getId();
                if ( id ==  SingletonBasesOperativas.getInstance().getLista().get(tablaBasesOperativas.getSelectedRow()).getId()) {
                    System.out.println("encontrado");
                    encontrado = true;
                    break;
                }
              
           }
        
        if (encontrado == true) {
           JOptionPane.showMessageDialog(null,"La base operativa seleccionada ya se encuentra asociada al cliente");
           encontrado = false;
        } else {
            AsociarBaseOperativaACliente asociador = new AsociarBaseOperativaACliente(SingletonBasesOperativas.getInstance().getLista().get(tablaBasesOperativas.getSelectedRow()));
            
            try {
                asociador.asociar();
                actualizarListas();

            } catch (Exception ex) {
                Logger.getLogger(AsociarBasesOperativasAClienteFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_botonAddFechaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        EliminarBaseOperativaACliente eliminador = new EliminarBaseOperativaACliente(listaBasesDelCliente.get(tablaBasesOperativasDelCliente.getSelectedRow()));
        try {
            eliminador.eliminar();
             actualizarListas();
        } catch (Exception ex) {
            Logger.getLogger(AsociarBasesOperativasAClienteFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        BasesOperativasCRUDFrame.getInstance().setVisible(true);
        this.setVisible(false);
      
        
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AsociarBasesOperativasAClienteFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AsociarBasesOperativasAClienteFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AsociarBasesOperativasAClienteFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AsociarBasesOperativasAClienteFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                try {
                    new AsociarBasesOperativasAClienteFrame().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(AsociarBasesOperativasAClienteFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAddFecha;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPaneCLIENTE;
    private javax.swing.JScrollPane jScrollPaneTOTAL;
    // End of variables declaration//GEN-END:variables
}
