
package view.ModificarFrames;

import command.productos.CargarProductosPedidoCommand;
import java.util.logging.Level;
import java.util.logging.Logger;
import model.Ficha;
import process.CRUDPedidos.ActualizarVariaciones;
import process.cargador.CargadorProductosPedido;
import process.parser.productos.ProductoParserJson;
import process.parser.productos.ProductoPedidoParserJson;
import view.pedidos.FichaPedidoFrame;

/**
 *
 * @author Aaron
 */
public class ModificarVariacionesFrame extends javax.swing.JFrame {

    Integer idPedido;
    Integer idProducto;
    FichaPedidoFrame ficha;
    
 
    
    
    public ModificarVariacionesFrame(Integer idPedido, Integer idProducto, FichaPedidoFrame ficha) {
        this.idPedido = idPedido;
        this.idProducto = idProducto;
        this.ficha = ficha;
        this.setLocationRelativeTo(ficha);
        initComponents();
        setVisible(true);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextFieldVariaciones = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setTitle("MODIFICAR DETALLES");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Detalles:");

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setText("Enviar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel1)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(jTextFieldVariaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(63, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldVariaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         ActualizarVariaciones actualizador = new ActualizarVariaciones(idPedido,idProducto,jTextFieldVariaciones.getText());
        try {
            actualizador.actualizar();
        } catch (Exception ex) {
            Logger.getLogger(ModificarVariacionesFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.setVisible(false);
       
        new CargarProductosPedidoCommand(new ProductoPedidoParserJson(), CargadorProductosPedido.getInstance()).executeTablaEnFicha(idPedido,ficha.getjTablaPedido());
    }//GEN-LAST:event_jButton1ActionPerformed

   
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTextFieldVariaciones;
    // End of variables declaration//GEN-END:variables
}
