/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.tarifas.simples;

import command.serviciosEspeciales.CargarServiciosEspecialesCommand;
import command.tarifas.CargarTarifasCommand;
import command.tarifas.CargarTiposDeTarifaCommand;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import model.serviciosEspeciales.ServicioEspecial;
import model.Tarifas.Tarifa;
import model.Tarifas.TipoDeTarifa;
import process.CRUDBasesOperativas.AsociarBaseOperativaACliente;
import process.CRUDServiciosEspeciales.AsociarServicioEspecialACliente;
import process.CRUDTarifas.AsociarTipoDeTarifaACliente;
import process.CRUDTarifas.EliminarTipoDeTarifaACliente;
import process.cargador.serviciosEspeciales.CargadorListaServiciosEspeciales;
import process.cargador.tarifas.CargadorListaTarifas;
import process.cargador.tarifas.CargadorListaTiposDeTarifa;
import process.parser.serviciosEspeciales.ServicioEspecialParserJson;
import process.parser.tarifas.TarifaParserJson;
import process.parser.tipoDeTarifas.TipoDeTarifaParserJson;
import view.fichaCliente.FichaCliente;
import view.serviciosEspeciales.JTablaServiciosEspeciales;
import view.tarifas.tiposDeTarifas.JTablaTiposDeTarifas;

/**
 *
 * @author loquat
 */
public class AsociarServiciosEspecialesAClienteFrame extends javax.swing.JFrame {

    /**
     * Creates new form AsociarTarifasAClienteFrame
     * @param listaLosTiposDelCliente
     * @param listaTodosLosTipos
     * @throws java.io.IOException
     */
    
    
    
    
     JTablaServiciosEspeciales tablaServiciosEspeciales;
     JTablaServiciosEspeciales tablaServiciosEspecialesDelCliente;
     List<ServicioEspecial> listaLosServiciosDelCliente;
     List<ServicioEspecial> listaTodosLosServicios;
   
     FichaCliente ficha;
     Integer idCliente;
     
    
    public AsociarServiciosEspecialesAClienteFrame(FichaCliente ficha) throws IOException {
        this.ficha = ficha;
        
        initComponents();
        tablaServiciosEspeciales = new JTablaServiciosEspeciales();
        tablaServiciosEspecialesDelCliente = new JTablaServiciosEspeciales();
        
//        this.listaLosServiciosDelCliente = ficha.getListaServiciosEspecialesDelCliente();
 //       this.listaTodosLosServicios = ficha.getListaTodosLosServiciosEspeciales();
      

      
        tablaServiciosEspecialesDelCliente.mostrarServiciosEspeciales(listaLosServiciosDelCliente);
        tablaServiciosEspeciales.mostrarServiciosEspeciales(listaTodosLosServicios);
        
        
        jScrollPaneTOTAL.setViewportView(tablaServiciosEspeciales);
        jScrollPaneCLIENTE.setViewportView(tablaServiciosEspecialesDelCliente);
        
        
       this.idCliente = ficha.getIdCliente();
     
        
        
    }
    
    public void actualizarListas() throws IOException {
    
       /*    CargarServiciosEspecialesCommand cargar = new CargarServiciosEspecialesCommand(new CargadorListaServiciosEspeciales(), new ServicioEspecialParserJson());
           CargarTiposDeTarifaCommand cargarTipos = new CargarTiposDeTarifaCommand(new CargadorListaTiposDeTarifa(), new TipoDeTarifaParserJson());
           List<ServicioEspecial> listaTarifasDiurno  =  cargar.executeLista(idCliente);
           listaLosServiciosDelCliente = new ArrayList<>();
           for (Tarifa lista1 : listaTarifasDiurno) {
                for (int j=0;j<listaTodosLosServicios.size();j++) {
                    if (lista1.getTipoDeTarifa().equals(listaTodosLosServicios.get(j).getId())) {
                        TipoDeTarifa tipo = new TipoDeTarifa();
                        tipo.setTipo(listaTodosLosServicios.get(j).getTipo());
                        tipo.setId(listaTodosLosServicios.get(j).getId());
                        listaLosServiciosDelCliente.add(tipo);

                    }
                }
            }
            
            cargar.executeListaNocturno(idCliente);
            ficha.actualizarListaTarifas(listaTarifasDiurno, listaTarifasDiurno, listaLosServiciosDelCliente);
            tablaServiciosEspecialesDelCliente.mostrarServiciosEspeciales(listaLosServiciosDelCliente);*/
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        botonAddFecha = new javax.swing.JButton();
        jScrollPaneTOTAL = new javax.swing.JScrollPane();
        jScrollPaneCLIENTE = new javax.swing.JScrollPane();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel47.setBackground(new java.awt.Color(51, 51, 255));
        jLabel47.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel47.setForeground(new java.awt.Color(51, 51, 51));
        jLabel47.setText("LISTADO TOTAL DE SERVICIOS ESPECIALES");

        jLabel48.setBackground(new java.awt.Color(51, 51, 255));
        jLabel48.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel48.setForeground(new java.awt.Color(51, 51, 51));
        jLabel48.setText("LISTADO SERVICIOS ESPECIALES DEL CLIENTE");

        botonAddFecha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/diasFestivos/arrow.png"))); // NOI18N
        botonAddFecha.setText("jButton1");
        botonAddFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAddFechaActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/tarifas/simples/flecha1.PNG"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel47)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPaneTOTAL, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(jButton1))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(botonAddFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)))))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel48)
                    .addComponent(jScrollPaneCLIENTE, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(228, 228, 228)
                        .addComponent(botonAddFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel47)
                            .addComponent(jLabel48))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPaneTOTAL, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPaneCLIENTE, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonAddFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAddFechaActionPerformed

/*        AsociarServicioEspecialACliente asociador = new AsociarServicioEspecialACliente(listaTodosLosServicios.get(tablaServiciosEspeciales.getSelectedRow()), idCliente);
        try {
            asociador.asociar();
            actualizarListas();

        } catch (Exception ex) {
            Logger.getLogger(AsociarTarifasAClienteFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
*/
    }//GEN-LAST:event_botonAddFechaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
  /*      EliminarServicioEspecialACliente eliminador = new EliminarServicioEspecialACliente(listaLosServiciosDelCliente.get(tablaServiciosEspecialesDelCliente.getSelectedRow()), idCliente);
         try {
             eliminador.eliminar();
               actualizarListas();
         } catch (Exception ex) {
             Logger.getLogger(AsociarTarifasAClienteFrame.class.getName()).log(Level.SEVERE, null, ex);
         }
        */
        
    }//GEN-LAST:event_jButton1ActionPerformed

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAddFecha;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPaneCLIENTE;
    private javax.swing.JScrollPane jScrollPaneTOTAL;
    // End of variables declaration//GEN-END:variables
}
