/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.gruas;

import DatosPrecargados.SingletonGruas;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import model.gruas.Grua;
import process.CRUDGruas.EliminarGrua;
import process.CRUDGruas.InsertarGrua;
import process.CRUDGruas.ModificarGrua;

/**
 *
 * @author gruasjoseantonio
 */
public class GruasCRUDFrame extends javax.swing.JFrame {

    
    private static GruasCRUDFrame instance;
    private  TablaGruasCRUD tabla;
    private  Integer filaSeleccionada;
    
    private GruasCRUDFrame() {
        initComponents();
     
        tabla = TablaGruasCRUD.getInstance();
        tabla.mostrarGruas(SingletonGruas.getInstance().getLista());
        jScrollPane1.setViewportView(tabla);
        setListenerEditarTabla();
        
    }

    
    
     public void setListenerEditarTabla() {
            jCheckBoxEditar.addItemListener(new ItemListener() {
               @Override
               public void itemStateChanged(ItemEvent e) {
                       
                   if (jCheckBoxEditar.isSelected()) {
                             tabla.habilitarEdicionTabla();
                             
                    } else {
                             
                             tabla.deshabilitarEdicionTabla();
                   }
                   
                   
               }
             });
    }
     
     
    public TablaGruasCRUD getTabla() {
        return tabla;
    }

    
    public void setFileSeleccionada (Integer filaSeleccionada) {
       this.filaSeleccionada = filaSeleccionada;
    }
    
    
    public void modicificarConductorGrua(Integer idConductor) {
    
        try {
            ModificarGrua modificar = new ModificarGrua(SingletonGruas.getInstance().getLista().get(filaSeleccionada).getId(), "conductor", idConductor.toString());
            modificar.modificarGrua();
            SingletonGruas.getInstance().actualizarLista();
            tabla.mostrarGruas(SingletonGruas.getInstance().getLista());
        } catch (IOException ex) {
            Logger.getLogger(GruasCRUDFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    
    public static GruasCRUDFrame getInstance() {
              if (instance == null) instance = new GruasCRUDFrame();
              return instance;
    
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jSeparator1 = new javax.swing.JSeparator();
        botonNuevaGrua = new javax.swing.JButton();
        botonEliminarGrua = new javax.swing.JButton();
        jCheckBoxEditar = new javax.swing.JCheckBox();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("GRUAS");
        setExtendedState(6);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Configuración de gruas");

        jScrollPane1.setForeground(new java.awt.Color(51, 51, 255));

        jSeparator1.setForeground(new java.awt.Color(0, 51, 255));

        botonNuevaGrua.setBackground(new java.awt.Color(255, 255, 255));
        botonNuevaGrua.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        botonNuevaGrua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/fichaCliente/plus.png"))); // NOI18N
        botonNuevaGrua.setText("Nueva grua");
        botonNuevaGrua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonNuevaGruaActionPerformed(evt);
            }
        });

        botonEliminarGrua.setBackground(new java.awt.Color(255, 255, 255));
        botonEliminarGrua.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        botonEliminarGrua.setText("Eliminar grua");
        botonEliminarGrua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEliminarGruaActionPerformed(evt);
            }
        });

        jCheckBoxEditar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jCheckBoxEditar.setText("Permitir editar tabla");
        jCheckBoxEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxEditarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jSeparator1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 465, Short.MAX_VALUE)
                        .addComponent(jCheckBoxEditar)
                        .addGap(34, 34, 34)
                        .addComponent(botonNuevaGrua, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(botonEliminarGrua, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonEliminarGrua, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonNuevaGrua, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBoxEditar))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonNuevaGruaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonNuevaGruaActionPerformed
        
        try {
            Grua grua = new Grua();
            InsertarGrua registrador = new InsertarGrua(grua);
            registrador.insertar();
            SingletonGruas.getInstance().actualizarLista();
            tabla.mostrarGruas(SingletonGruas.getInstance().getLista());
        } catch (Exception ex) {
            Logger.getLogger(GruasCRUDFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        

    }//GEN-LAST:event_botonNuevaGruaActionPerformed

    private void botonEliminarGruaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEliminarGruaActionPerformed
        
        try {
            Grua grua = new Grua();
            grua.setId((Integer) tabla.getValueAt(tabla.getInstance().getSelectedRow(), 0));
            EliminarGrua eliminar = new EliminarGrua(grua);
            eliminar.eliminar();
            SingletonGruas.getInstance().actualizarLista();
            tabla.mostrarGruas(SingletonGruas.getInstance().getLista());
        

        } catch (Exception ex) {
            Logger.getLogger(GruasCRUDFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_botonEliminarGruaActionPerformed

    private void jCheckBoxEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxEditarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxEditarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GruasCRUDFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GruasCRUDFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GruasCRUDFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GruasCRUDFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
               GruasCRUDFrame.getInstance().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonEliminarGrua;
    private javax.swing.JButton botonNuevaGrua;
    private javax.swing.JCheckBox jCheckBoxEditar;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
