/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.marcas;

import DatosPrecargados.SingletonMarcas;
import command.vehiculos.CargarModelosCommand;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import model.vehiculos.Marca;
import process.CRUDMarcas.EliminarMarca;
import process.CRUDMarcas.InsertarMarca;
import process.cargador.vehiculos.CargadorListaModelo;
import process.parser.vehiculos.ModeloParserJson;
import view.fichasVehiculos.FichaVehiculo;

public class MarcasCRUDFrame extends javax.swing.JFrame {

    
    
    private static MarcasCRUDFrame instance;
    
    
    
    public static MarcasCRUDFrame getInstance() {
    
        if (instance == null) instance = new MarcasCRUDFrame();
        return instance;
    }
    
    private MarcasCRUDFrame() {
        initComponents();
        jScrollPaneMarcas.setViewportView(JTablaMarcas.getInstance());
        jScrollPaneModelos.setViewportView(JTablaModelos.getInstance());
        actualizarTablaMarcas();
        setListenerEditarTabla();
   
    }
    
    public void actualizarTablaMarcas() {
        SingletonMarcas.getInstance().actualizarLista();
        JTablaMarcas.getInstance().mostrar(SingletonMarcas.getInstance().getLista());
    }

    
    public void actualizarTablaModelos(int idMarcaPadre) {
        try {
            CargarModelosCommand cargar = new CargarModelosCommand(new CargadorListaModelo(), new ModeloParserJson());
            JTablaModelos.getInstance().mostrar(cargar.executePorIdMarcaPadre(idMarcaPadre));
            
        } catch (IOException ex) {
            Logger.getLogger(MarcasCRUDFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
     }

    
      public void setListenerEditarTabla() {
            jCheckBoxEditar.addItemListener(new ItemListener() {
               @Override
               public void itemStateChanged(ItemEvent e) {
                       
                   if (jCheckBoxEditar.isSelected()) {
                              JTablaMarcas.getInstance().habilitarEdicionTabla();
                             JTablaModelos.getInstance().habilitarEdicionTabla();
                             
                    } else {
                               JTablaMarcas.getInstance().habilitarEdicionTabla();
                             JTablaModelos.getInstance().deshabilitarEdicionTabla();
                   }
                   
                   
               }
             });
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPaneMarcas = new javax.swing.JScrollPane();
        botonNuevaGrua = new javax.swing.JButton();
        botonEliminarGrua = new javax.swing.JButton();
        jCheckBoxEditar = new javax.swing.JCheckBox();
        jScrollPaneModelos = new javax.swing.JScrollPane();
        botonNuevoModelo = new javax.swing.JButton();
        botonEliminarModelo = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Configuración de marcas");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        botonNuevaGrua.setBackground(new java.awt.Color(255, 255, 255));
        botonNuevaGrua.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        botonNuevaGrua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/fichaCliente/plus.png"))); // NOI18N
        botonNuevaGrua.setText("Nueva marca");
        botonNuevaGrua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonNuevaGruaActionPerformed(evt);
            }
        });

        botonEliminarGrua.setBackground(new java.awt.Color(255, 255, 255));
        botonEliminarGrua.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        botonEliminarGrua.setText("Eliminar marca");
        botonEliminarGrua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEliminarGruaActionPerformed(evt);
            }
        });

        jCheckBoxEditar.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBoxEditar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jCheckBoxEditar.setText("Permitir editar tabla");

        botonNuevoModelo.setBackground(new java.awt.Color(255, 255, 255));
        botonNuevoModelo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        botonNuevoModelo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/fichaCliente/plus.png"))); // NOI18N
        botonNuevoModelo.setText("Nuevo modelo");
        botonNuevoModelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonNuevoModeloActionPerformed(evt);
            }
        });

        botonEliminarModelo.setBackground(new java.awt.Color(255, 255, 255));
        botonEliminarModelo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        botonEliminarModelo.setText("Eliminar modelo");
        botonEliminarModelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEliminarModeloActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 204));
        jLabel1.setText("MARCAS");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 204));
        jLabel2.setText("MODELOS");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addComponent(jCheckBoxEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(176, 176, 176))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPaneMarcas)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(botonNuevaGrua, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(botonEliminarGrua, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(50, 50, 50)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(botonNuevoModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonEliminarModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPaneModelos))
                .addGap(117, 117, 117))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(252, 252, 252)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(254, 254, 254))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPaneMarcas, javax.swing.GroupLayout.DEFAULT_SIZE, 524, Short.MAX_VALUE)
                    .addComponent(jScrollPaneModelos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonNuevaGrua, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonEliminarGrua, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonNuevoModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonEliminarModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jCheckBoxEditar)
                .addGap(47, 47, 47))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonNuevaGruaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonNuevaGruaActionPerformed
     
    
        try {
            Marca marcaR = new Marca();
            InsertarMarca registrador = new InsertarMarca(marcaR);
            registrador.inserta();
            actualizarTablaMarcas();
        } catch (Exception ex) {
            Logger.getLogger(MarcasCRUDFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
      
    }//GEN-LAST:event_botonNuevaGruaActionPerformed

    private void botonEliminarGruaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEliminarGruaActionPerformed

        try {
            EliminarMarca eliminar = new EliminarMarca(JTablaMarcas.getInstance().getTablaCRUDModelo().getListaMarcas().get(JTablaMarcas.getInstance().getSelectedRow()));
            eliminar.eliminar();
            actualizarTablaMarcas();
        } catch (Exception ex) {
            Logger.getLogger(FichaVehiculo.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_botonEliminarGruaActionPerformed

    private void botonNuevoModeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonNuevoModeloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonNuevoModeloActionPerformed

    private void botonEliminarModeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEliminarModeloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonEliminarModeloActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MarcasCRUDFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MarcasCRUDFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MarcasCRUDFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MarcasCRUDFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                MarcasCRUDFrame.getInstance().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonEliminarGrua;
    private javax.swing.JButton botonEliminarModelo;
    private javax.swing.JButton botonNuevaGrua;
    private javax.swing.JButton botonNuevoModelo;
    private javax.swing.JCheckBox jCheckBoxEditar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPaneMarcas;
    private javax.swing.JScrollPane jScrollPaneModelos;
    // End of variables declaration//GEN-END:variables
}
